name: 'Deploy App'
on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: self-hosted
    steps:

      - name: Checkout and run app
        uses: actions/checkout@v3

      - name: Run app
        run: |
          cd app
          docker compose up -d --force-recreate
